# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0002_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=128)),
                ('post_datetime', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
            ],
        ),
    ]
